name: CI Pipeline - FlutterIntra

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code (lint)
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Build Docker image
        run: docker build -t flutterintra:latest .